### ISSUE TITLE
Time processing after scene changes

### ISSUE THREAD

**Issue by MirialisT** [MirialisT/Project-Ataraxia#5]
### OVERVIEW
Need to decide whether keep scene active, but invisible, or store it and process inactive time on-load.
Probably will settle for active-invisible parts of town, and inactive-processing towns in world map. Try everything.
[Docs](https://docs.godotengine.org/en/stable/tutorials/scripting/change_scenes_manually.html)
- [x] Make singleton scene changer (make funcs probably for every option)
## "Delete the existing scene" option
- [x] Do it (change-scene-to-file)
- [x] #6
- [x] Test performance with it (yeah, I will think about performance already at this state)
- [x] Test signals
## "Hide the existing scene" option
- [x] Do it
- [x] Test time-processing with it (should work just fine)
- [x] Test performance with it
- [x] Test signals
## "Remove the existing scene from the tree" option
- [x] Do it
- [x] Test time-processing with it (it stops processing, so same approach as with delete option)
- [x] Test performance with it
- [x] Test signals
### TODO:
- [x] Try every option and choose the best

**Comment by MirialisT** [comment]
Third option technically solved #6, so first opt sucks, second would be cumbersome in long-run. Third is a go-to.
